language: node_js
node_js: node
deploy:
  provider: heroku
  app: letsroll
  api_key:
    secure: lCsQQigBp6P3tXWTfDMXqAwwLsny//GLErMhLk6Vlqaj1lFPv8i/i44YLxPWhfPf+OQyJn5laF+OI4wirCnlyOI1hrwBwmaycug0qwiXJIzFcxEGDATs+Lo1b5uODK3LIAQwJzHfybFYBeEI+aOynWSHYhUdCuFC9qH+8kWhpOuYSPQaSI+DD2jevk5KfqwM7npjrjpdVaRhpCSvbYaGydR85p1w1bpFJ1mhXUR3F5HKIrWjaTr8KzuDuW5A4Ts/+BleujaRQ7KNvCQeKshsateMCI8tMk7a56IS+1NK3dJ4fLbc+uXFxWEsXf99y0ekREWY7X9+UjPd8HiGn+SJ0fI3KTGOtV/LIxX3zB3CiH/aAIyI8UDhyZiX5OONDcCCWYZHe9CfLtn5KsnrY0DtC4Zue+dd9Snoo+gPC4cm47B1INBRRu6/0nuB+qamF1Q+vc2WayK3xpdBdAOCE/QU6wgtcOgnF9Hpy4zzLX87S1tEMMTm5x2Io4KbJ6swhQDIsn1bqdxO4EBEt7goSQhUUzuGboGd8xw0SjKjz2Vpuw3xtWB9fxJeUBwbU64yAqrNMmF56YL5pYikz123Anp1+crHYjKGbYEATcIs2tYNFxszCBDtuNqtF11RH+eJ5P12CYTR+3xhX7AHtbWlYEd7S3E2nVy+NwfscaTQl/chYZY=
